import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Snack Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* --- HEADER: Snack Hub --- */}
        <header className="w-full py-8 bg-gray-100 dark:bg-gray-800 flex justify-center">
          <h1 className="text-5xl font-bold text-center">Snack Hub</h1>
        </header>

        {/* --- SEITENINHALT bleibt hier --- */}
        {children}
      </body>
    </html>
  );
}

