import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Snack Hub",
  description: "Generated by create next app",
};

/* Website öffnen: 

npm install

npm run dev

ready - started server on http://localhost:3000

*/

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full py-8 bg-gray-100 dark:bg-gray-800 flex justify-center">
          <h1 className="text-5xl font-bold text-center">Snack Hub</h1>
        </header>
        {children}
      </body>
    </html>
  );
}

function Header() {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <header className="w-full py-4 bg-gray-100 dark:bg-gray-800 flex items-center justify-between px-8 shadow-md">
      {/* Logo + Titel */}
      <div className="flex items-center space-x-4">
        <Image
          src="/logo.png" // Pfad zu deinem Logo (im public/ Ordner ablegen!)
          alt="Snack Hub Logo"
          width={50}
          height={50}
        />
        <h1 className="text-3xl font-bold text-gray-800 dark:text-white">
          Snack Hub
        </h1>
      </div>

      {/* Dropdown Menü */}
      <div className="relative">
        <button
          onClick={() => setIsOpen(!isOpen)}
          className="bg-gray-200 dark:bg-gray-700 text-gray-900 dark:text-white px-4 py-2 rounded-md hover:bg-gray-300 dark:hover:bg-gray-600 transition"
        >
          Menü ▾
        </button>

        {isOpen && (
          <div className="absolute right-0 mt-2 w-48 bg-white dark:bg-gray-700 border dark:border-gray-600 rounded-md shadow-lg z-50">
            <Link
              href="/"
              className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 text-gray-800 dark:text-white"
            >
              Startseite
            </Link>
            <Link
              href="/produkte"
              className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 text-gray-800 dark:text-white"
            >
              Produkte
            </Link>
            <Link
              href="/kontakt"
              className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 text-gray-800 dark:text-white"
            >
              Kontakt
            </Link>
          </div>
        )}
      </div>
    </header>
  );
}
